modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mo_tools"
version="1.0.0"
displayName="Mo Tools"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Hussein El Karargi, MCreator"

[[dependencies.mo_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




